### ISSUE TITLE
Error "Bad allocation", Notedpad++ crash while comparing two CSV files using Compare plugin 

### ISSUE THREAD

**Issue by RandomUser0815** [pnedev/compare-plugin#136]
### Description of the Issue
Notedpad++ 7.4.1 and 7..4.2 (Windows 10) and 7.3.3 (Windows 10) crash while comparing two files. Error "Bad Allocation" is displayed.

### Steps to Reproduce the Issue

1. Use Compare plugin 1.5.6.2 or 2.0
2. Use Plugin Manager 1.3.5 or 1.4.5
3. Compare two CSV files of 330 kb and 394 kb size.

### Expected Behavior
I would expect that the differences between both files are displayed. Unfortunately I can not share the files.

### Actual Behavior
![notepad _crash](https://user-images.githubusercontent.com/30178968/28214848-31bd72fa-68ac-11e7-899f-850ae3e01d4b.png)

### Debug Information
Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)   (actually Windows Server 2008 R2)
Plugins : ComparePlugin.dll NppColumnSort.dll sql.dll 

Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit) (locally on my Laptop)
Plugins : ComparePlugin.dll mimeTools.dll NppColumnSort.dll NppConverter.dll NppExport.dll PluginManager.dll sql.dll

**Comment by pnedev** [comment]
Hi,

Thank you for the report @RandomUser0815 , I'm preparing the next plugin version and I have already fixed several bugs that were leading to this problem.

Is the issue consistently reproducible on your side?

BR

**Comment by RandomUser0815** [comment]
Yes. I am able to reproduce, the issue. I still have the files, that caused it.

**Comment by pnedev** [comment]
OK, that's good.
Can you try this plugin version for me please?
x86: https://ci.appveyor.com/api/buildjobs/7btppvpc6hhlkr8o/artifacts/ComparePlugin.dll
It is bigger because it is compiled with debug info.
It is a preliminary development version and you will find some differences vs. v2.0 and some thing might not work or look OK but the compare process should be fine and the plugin should not crash.

Please write back if the issue persists.
Thank you.

**Comment by RandomUser0815** [comment]
I installed the beta plugin 3.0 and notedpad++ 7.4.2 still crashed. Where may I find the crash log or debug info? Please find attached the windows crash report.

[Report.wer.txt](https://github.com/pnedev/compare-plugin/files/1189840/Report.wer.txt)

**Comment by pnedev** [comment]
Hello @RandomUser0815 ,

Thank you for testing and writing back.
Did the "bad allocation" message appear again or just the N++ crashed?

**Comment by RandomUser0815** [comment]
Yes, the message did appear again.

**Comment by pnedev** [comment]
OK, I'll investigate further, thank you.

**Comment by pnedev** [comment]
@RandomUser0815 ,
Could you do one more test for me?
Can you run the same test with the beta plugin version but without the Navigation Bar (just switch it off before running the test)?
Thank you.

**Comment by RandomUser0815** [comment]
Still the error message is displayed.

**Comment by pnedev** [comment]
Thank you.

**Comment by githubmike63** [comment]
Sorry for jumping in.
I just updated to the new version 7.5.1 of N0tepad++ 32 bit. I am using it often to compare pcl print data. Now I always have the problem that during comparing the software is hanging. Progress bar is in the middel.
Issue is reproducable using the two files provided

[temp.zip](https://github.com/pnedev/compare-plugin/files/1398158/temp.zip)

.
I have a Windows 10 enterprise system build 15063.
I do not have the error message but also the hanging on CSV.
I tried the before shared beta of the dll with the same result.

**Comment by pnedev** [comment]
Hello @githubmike63 ,

The Compare plugin works on a line-by-line basis and it also tries to resolve line differences.
Now your sample file _'standard.prn'_ has several lines (57 to 61) that are enormous in length (line 61 is 82660 symbols alone) which leads to a HUGE increase in the compare time.

I have made a lot of plugin improvements since this thread was opened although it is not ready for a release yet but if you like you can try this development version:
- x86: https://ci.appveyor.com/api/buildjobs/xwex2r4gqlc9g0sd/artifacts/ComparePlugin.dll

It manages to process your files considerably faster but nevertheless you need to be patient.
I'll consider disabling line differences check for particularly long lines. That will shorten the compare time in your case a lot.
Write back if you need further support.


Hello @RandomUser0815 ,

A lot of time has passed since you filed this issue but if you are reading this and you still have the CSV files causing the crash and are willing to try again please test with the linked development binary above.
Thanks.

BR
