### ISSUE TITLE
Wrong file is activated in Two-Views mode

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#59]
Hello Pavel,

A minor regression after the last refactoring.

STR:
Set "Old file position" to left/top.
Have two files in Two-Views mode.
Activate the file at top.
Compare.

Result:
The file at bottom is activated.

NOTE: if you set "Old file position" to right/bottom, the file at *top* is always activated.

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, I did that on purpose - I activate the new file on successful compare.
Perhaps that is unneeded though... Maybe it's better if the focus remains in the file compare was started from.
On the other hand, in case "Set first" is used then the focus will inevitably be in the second file...

What do you think is best after successful compare,
1 - to always focus on the new file (current implementation) or
2 - to focus on the file that had the focus when "Compare" was triggered?

Thanks.

BR

**Comment by xylographe** [comment]
Perhaps, `if (First is: new file) { focus on new file } else { focus on last focused file }`?

**Comment by pnedev** [comment]
That won't do but
`if (First is: new file && "Set First" was used) { focus on new file } else { focus on last focused file }`
is OK, thanks.

Let's wait to see what Yaron thinks about it.

What's your preference about the focus? The check you suggested?

BR

**Comment by xylographe** [comment]
My preference is  "1 - to always focus on the new file (current implementation)".

**Comment by pnedev** [comment]
Thanks @xylographe .

**Comment by Yaron10** [comment]
Hello,

I think the concept should be simple: CP should not interfere and leave the focus where it was.

Indeed, `if (First is: new file && "Set First" was used) { focus on new file }` should be an exception.
Because it's not consistent. :) I'm joking!

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Sounds OK, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you. I appreciate it.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Fixed in master, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much.

Have a nice weekend.

**Comment by Yaron10** [comment]
Hello Pavel,

The problem still exists If you compare equal files.

STR:
Double-View mode.
Compare two equal files.

Result:
The file in the other view is activated.

NOTE:
The problem also exists If you compare equal files in Single-View mode.
In this case it seems a bit arbitrary (though I'm sure it isn't).
Please try with three files open, different tabs order and different "Old file position" setting). 

Thank you.
BR

**Comment by pnedev** [comment]
OK, Yaron,
I'll check that soon, thanks for reporting.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much. I appreciate it.

BR

**Comment by pnedev** [comment]
Hello Yaron,

This should be fixed in latest master commit.
Could you please check? Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much. Great work. :+1: 

An old issue is back (this is a tough puzzle :) ).

*Case 1:*
Set "Old file position" to "Right/Bottom".
Start NPP.
Open two equal files.
Compare.
Close? - Yes.

*Case 2:*
Set "Old file position" to "Left/Top".
Start NPP.
Open two equal files.
Move to Other View.
Activate the file at top.
Compare.
Close? - Yes.

*Case 3:*
Start NPP.
Open two *different* files.
Move to Other View.
Compare.
Close the file at top.

**Result:**
You are in Single-View Sub-View.
***
I appreciate your patience.

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

Hm, that regression had happened before the current fix.
Anyway:

Case 1 is fixed.
Case 2 is fixed.

Case 3 is normal behavior and I intend to leave it as it is. I'm pretty sure we have discussed that before. The thing is, when you manually move the file before compare you explicitly force it to be in the other (sub) view. Then when you close the other file (in main view) the current one is restored as it was before the compare -> it remains in the sub-view.
Imagine that you have 1 file (A) in main view and two files in the sub view (B and C).
Now you compare A and B.
Close A.
Now B and C remain in the sub view and we are in single view. Moving B to main view would be weird in that case.
Of course I can check if B will be the only file remaining after the close and move it to the main view but I think that is too much.
I'm sure you would like such functionality :)
@xylographe , could you share your opinion on this?

Thank you both.

BR

**Comment by pnedev** [comment]
Hi again,

Yaron,

You can try to open two files A and B in main and sub view respectively and then without comparing just close A (the file in the main view). You'll end-up in single sub view "naturally".
I'm sure you know that already it is just an example.
Thanks.

BR

**Comment by xylographe** [comment]
Hello Pavel,

Same opinion as before in similar cases: CP should restore whenever possible. In this case 'restore' means doing absolutely nothing, which is the current behaviour. Hence, I agree with "*Case 3 is normal behavior and I intend to leave it as it is.*"

**Comment by pnedev** [comment]
Thanks for the feedback @xylographe .

**Comment by Yaron10** [comment]
Hello Pavel,

> Case 1 is fixed.
> Case 2 is fixed.

Thank you. I appreciate it.

Case 3.
My confusion. My mistake. 
Sorry.

BR

**Comment by pnedev** [comment]
Hello Yaron,
No problem.
BR
